window.onload = function() {

// news	
loadEntries('https://news.google.com/rss/search?q=when:24h+allinurl:reuters.com&ceid=US:en&hl=en-US&gl=US','reuters')
loadEntries('http://rss.nytimes.com/services/xml/rss/nyt/World.xml','nyt')
loadEntries('http://rss.cnn.com/rss/edition.rss','cnn')
loadEntries('https://www.theguardian.com/international/rss','guardian')
loadEntries('http://feeds.bbci.co.uk/news/world/rss.xml','bbc')
loadEntries('http://www.huffingtonpost.com/section/front-page/feed','huffpost')
loadEntries('https://www.vox.com/rss/index.xml','vox')
loadEntries('http://rssfeeds.usatoday.com/usatoday-NewsTopStories','usatoday')
loadEntries('http://feeds.washingtonpost.com/rss/politics','washingtonpost')
loadEntries('http://www.aljazeera.com/xml/rss/all.xml','aljazeera')
loadEntries('https://www.rt.com/rss/news/','rt')
loadEntries('https://theintercept.com/feed/?lang=en','intercept')
loadEntries('https://www.thenation.com/feed/?post_type=article','nation')
loadEntries('http://time.com/feed/','time')
loadEntries('http://feeds.slate.com/slate','slate')
loadEntries('https://www.newsweek.com/rss','newsweek')
// loadEntries('https://www.factcheck.org/feed/','factcheck')

// tech
loadEntries('https://mashable.com/rss/','mashable')
loadEntries('http://www.theverge.com/rss/index.xml','verge')
loadEntries('http://feeds.feedburner.com/TechCrunch/?format=xml','techcrunch')
loadEntries('http://feeds2.feedburner.com/thenextweb/?format=xml','tnw')
loadEntries('https://www.wired.com/feed/','wired')
loadEntries('https://gizmodo.com/rss','gizmodo')
loadEntries('https://www.cnet.com/rss/news/','cnet')
loadEntries('https://www.engadget.com/rss.xml','engadget')
loadEntries('http://feeds.arstechnica.com/arstechnica/index','arstechnica')
loadEntries('https://www.digitaltrends.com/feed/','digitaltrends')
loadEntries('https://www.zdnet.com/news/rss.xml','zdnet')

// finance
loadEntries('https://news.google.com/rss/search?q=when:24h+allinurl:bloomberg.com&ceid=US:en&hl=en-US&gl=US','bloomberg')
loadEntries('http://www.forbes.com/news/index.xml','forbes')
loadEntries('https://www.economist.com/feeds/print-sections/74/international.xml','economist')
loadEntries('http://www.cnbc.com/id/100003114/device/rss/rss.html','cnbc')
loadEntries('http://www.ft.com/rss/world','ft')
loadEntries('http://feeds.feedburner.com/entrepreneur/latest','entrepreneur')
loadEntries('http://www.wsj.com/xml/rss/3_7014.xml','wsj')
loadEntries('https://www.inc.com/rss/','inc')
loadEntries('http://www.businessinsider.com/rss','businessinsider')
loadEntries('https://feeds.feedburner.com/fastcompany/headlines','fastcompany')
loadEntries('http://feeds.hbr.org/harvardbusiness/','hbr')

// sports
loadEntries('http://www.espn.com/espn/rss/news','espn')
loadEntries('https://deadspin.com/rss','deadspin')
loadEntries('https://api.foxsports.com/v1/rss','foxsports')
loadEntries('http://newsrss.bbc.co.uk/rss/sportonline_world_edition/front_page/rss.xml','bbcsport')
loadEntries('http://feeds.feedburner.com/sportsblogs/sbnation.xml','sbnation')
loadEntries('https://sports.yahoo.com/rss/','yahoosports')

// culture
loadEntries('http://www.billboard.com/articles/rss.xml','billboard')
loadEntries('https://www.buzzfeed.com/index.xml','buzzfeed')
loadEntries('https://www.avclub.com/rss','avclub')
loadEntries('https://www.vice.com/en_us/rss','vice')
loadEntries('http://www.mtv.com/news/feed/','mtv')
loadEntries('http://rss.tvguide.com/breakingnews','tvguide')
loadEntries('http://ew.com/feed/','ew')
loadEntries('http://people.com/feed/','people')
loadEntries('http://syndication.eonline.com/syndication/feeds/rssfeeds/topstories.xml','eonline')
loadEntries('http://www.rollingstone.com/rss','rollingstone')
loadEntries('http://www.tmz.com/rss.xml','tmz')
loadEntries('http://feeds.feedburner.com/variety/news/frontpage','variety')
loadEntries('http://feeds.feedburner.com/nymag/vulture','vulture')

// games 
loadEntries('https://www.polygon.com/rss/index.xml','polygon')
loadEntries('http://feeds.ign.com/ign/all','ign')
loadEntries('https://www.gamespot.com/feeds/mashup/','gamespot')
loadEntries('https://kotaku.com/rss','kotaku')
loadEntries('http://www.pcgamer.com/rss/','pcgamer')
loadEntries('https://www.eurogamer.net/?format=rss','eurogamer')
loadEntries('http://feeds.feedburner.com/RockPaperShotgun','rps')
loadEntries('http://www.gameinformer.com/feeds/TheFeedRSS.aspx','gameinformer')

// science
loadEntries('http://www.popsci.com/rss.xml','popsci')
loadEntries('http://feeds.feedburner.com/AllDiscovermagazinecomContent','discovermag')
loadEntries('http://feeds.nature.com/nature/rss/current','nature')
loadEntries('http://www.sciencemag.org/rss/news_current.xml','sciencemag')
loadEntries('https://news.nationalgeographic.com/index.rss','natgeo')
loadEntries('http://www.bbc.com/future/feed.rss','bbcfuture')
loadEntries('https://www.wired.com/category/science/feed/','wiredscience')
loadEntries('https://www.space.com/home/feed/site.xml','space')
loadEntries('http://feeds.newscientist.com/all','newscientist')
loadEntries('https://www.futurity.org/feed/','futurity')
loadEntries('http://rss.sciam.com/ScientificAmerican-Global','scientificamerican')
loadEntries('http://rssfeeds.webmd.com/rss/rss.aspx','webmd')
loadEntries('http://feeds.feedblitz.com/greatist','greatist')

// discover
loadEntries('https://medium.com/feed/tag/popular','medium')
loadEntries('https://www.reddit.com/r/all/top/.rss','reddit')
loadEntries('https://www.producthunt.com/feed','producthunt')

}